config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  get 'cart' => 'carts#show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact

  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products, only: [:index, :show]

  namespace :backend do
    resources :categories
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true

  mount_uploader :image, CategoryImageUploader

  has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true

  belongs_to :category
  has_many :line_items, dependent: :destroy

  mount_uploader :image, ProductImageUploader

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_categories, :current_cart

  private

  def set_categories
    @categories = Category.all.order(:position)
  end

  def current_cart
    Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end


# create products with columns: title, description:text,
# price:decimal (:precision => 8, :scale => 2),
#                                   image, rating
# gem 'russian'
  # def to_param
  #   "#{id}-#{title.parameterize}"
  # end

# create carts, actions show, destroy

      # <% if session[:cart_id] %>
      #     В корзине товара на сумму <%= number_to_currency(Cart.find(session[:cart_id]).total_price, :precision => 0, :unit => "грн.", :separator => ",", :delimiter => "", :format => "%n %u") %>
      #     <%= link_to "Перейти »", carts_path%>
      # <% else %>
      # Корзина пуста
      # <% end %>

# create LineItems,
# product_id, cart_id, quantity:integer (default: 1), order_id, title, price


# create orders
#          name, email, phone, address, status, order_details

  # def add_line_items_from_cart(cart)
  #   cart.line_items.each do |item|
  #     item.cart_id = nil
  #     line_items << item
  #   end
  # end

app/controllers/backend/categories_controller.rb
# encoding: utf-8
class Backend::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.order(:position)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to backend_category_path(@category)
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to backend_category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to backend_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :short_description, :description,
                                     :position, :meta_title, :meta_description,
                                     :meta_keywords, :image, :remote_image_url)
  end
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base

  def show
    @cart = Cart.find(session[:cart_id])
    @line_items = @cart.line_items

    @total_amount = 0
    # @total_amount = @cart.products.sum(&:price)
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < InheritedResources::Base

  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.line_items.build(product: product)
    if @line_item.save
      redirect_to cart_path, notice: 'Отличная покупка!'
    else
      redirect_to :back
    end


  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.where(id: params[:category]).first if params[:category].present?
    @products = if @category.present?
                  @category.products
                else
                  Product.all
                end
  end

  def show
    @product = Product.find(params[:id])
  end

  def search_suggestions
    query = params[:query]
    results = if params[:query].present?
                Product.where('title ILIKE ? OR description ILIKE ?', "%#{query}%", "%#{query}%").select(:title).collect(&:title)
              else
                []
              end
    render json: results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/backend/categories/_form.html.erb
<%= form_for(@category, url: @category.new_record? ? backend_categories_path : backend_category_path, html: {class: 'form-horizontal'}) do |f| %>
  <% if @category.errors.present? %>
    <div role="alert" class="alert alert-danger alert-dismissible fade in">
      <button aria-label="Close" data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span></button>
      <% @category.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>
  <div class="col-md-6">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :position %>
        <%= f.number_field :position, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :short_description %>
        <%= f.text_area :short_description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :image, "Фото" %>
        <div class="controls">
          <%= f.file_field :image %>
        </div>
        <div>
          <%= f.label :remote_image_url, "Cсылка на изображение" %>
          <div class="controls">
            <%= f.text_field :remote_image_url, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :meta_title %>
        <%= f.text_field :meta_title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :meta_description %>
        <%= f.text_area :meta_description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :meta_keywords %>
        <%= f.text_area :meta_keywords, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/backend/categories/edit.html.erb
<div class="page-header">
  <h2>Редактирование категории "<%= @category.title %>"</h2>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @category.image_url, style: 'width: 100px;' if @category.image? %>
    </div>
    <div class="col-md-6 text-right">
      <%= link_to 'New Category', new_backend_category_path, class: 'btn btn-primary' %>
      <%= link_to "Categories List", backend_categories_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/backend/categories/index.html.erb
<h2>Categories</h2>
<div class="text-right">
  <%= link_to 'New Category', new_backend_category_path, class: 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>image</th>
      <th>Name</th>
      <th>Position</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <th scope="row"><%= category.id %></th>
        <td><%= image_tag category.image_url, style: 'width: 50px;' if category.image? %></td>
        <td><%= category.title %></td>
        <td><%= category.position %></td>
        <td>
          <%= link_to "Show", backend_category_path(category), class: 'btn btn-info' %>
          <%= link_to "Edit", edit_backend_category_path(category), class: 'btn btn-primary' %>
          <%= link_to "Delete", backend_category_path(category), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/backend/categories/new.html.erb
<div class="page-header">
  <h2>Новая категория</h2>
  <div class="row">
    <div class="col-md-12 text-right">
      <%= link_to "Categories List", backend_categories_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<%= render 'form' %>

app/views/backend/categories/show.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-md-4">
      <h2>Категория "<%= @category.title %>"</h2>
    </div>
    <div class="col-md-8 text-right">
      <%= link_to "Categories List", backend_categories_path, class: 'btn btn-primary' %>
      <%= link_to 'Edit Category', edit_backend_category_path(@category), class: 'btn btn-primary' %>
      <%= link_to 'Delete', backend_category_path(@category), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="col-md-12">
      <p>
        <%= image_tag @category.image_url, style: 'width: 100%;' %>
      </p>
    </div>
  </div>
  <div class="col-md-6">
    <div class="col-md-12">
      <p><strong>position:</strong> <%= @category.position %></p>
      <p>
        <strong>short_description:</strong> <%= @category.short_description %>
      </p>
      <p>
        <strong>description:</strong> <%= @category.description %>
      </p>
      <p><strong>meta_title:</strong> <%= @category.meta_title %></p>
      <p><strong>meta_description:</strong> <%= @category.meta_description %></p>
      <p><strong>meta_keywords:</strong> <%= @category.meta_keywords %></p>
    </div>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-6">
  <h1>В корзинке:</h1>
  <table class="table">
    <% @line_items.each_with_index do |line_item, index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= link_to line_item.product.title, product_path(line_item.product) %></td>
      <td>1</td>
      <td><%= number_to_currency(line_item.product.price) %></td>
      <% @total_amount += line_item.product.price %>
    </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td><%= number_to_currency(@total_amount) %></td>
    </tr>
  </table>
</div>
<div class="col-md-6">
  <h1>Куда доставить?</h1>
  <div>Имя (инпут)</div>
  <div>Телефон (инпут)</div>
  <%= link_to 'Оформить покупку', '#' %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-header-main">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-header" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-header">
      <div class="main-header row">
        <div class="col-md-6">
          <div class="phones">
            <%= icon 'phone' %>
            (050) 741-07-75 / (068) 555-33-61
          </div>
        </div>
        <div class="col-md-6">
          <div class="user-block pull-right">
            <%= link_to 'Вход', '#' %>
            /
            <%= link_to 'Регистрация', '#' %>
            |
            <%= link_to raw("<span>Корзина</span> #{ icon 'shopping-cart' }"), cart_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
<div class="logo-block hidden-xs">
  <div class="container">
    <div class="col-md-4">
      <%= form_tag('#', method: 'get', class: 'form-horizontal', id: 'header-search') do %>
          <div class="form-group">
            <div class="input-box">
              <%= text_field_tag(:q, (params[:q].present? ? params[:q] : nil), class: 'form-control', placeholder: 'Поиск', autocomplete: 'off') %>
              <i class="fa fa-search form-control-submit" aria-hidden="true" onclick="document.getElementById('header-search').submit();"></i>
              <ul id="results">
              </ul>
            </div>
          </div>
      <% end %>
    </div>
    <div class="col-md-4 text-center">
      <%= link_to image_tag('logo.png'), root_path %>
    </div>
    <div class="col-md-4">
      <div class="social-links pull-right">
        <%= link_to icon('vk'), '#' %>
        <%= link_to icon('odnoklassniki'), '#' %>
        <%= link_to icon('facebook'), '#' %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar navbar-default navbar-header-category">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-category" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-category">
      <ul class="nav navbar-nav">
        <% @categories.each do |category| %>
          <li class="<%= current_page?(products_path) && @category.present? && @category == category ? 'active' : '' %>">
            <%= link_to category.title, products_path(category: category.id) %>
          </li>
        <% end %>
        <li class="<%= current_page?(about_path) ? 'active' : '' %>">
          <%= link_to 'О нас', about_path %>
        </li>
        <li class="<%= current_page?(contact_path) ? 'active' : '' %>">
          <%= link_to 'Контакты', contact_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puhovik</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/pages/home.html.erb
<%= session[:cart_id] %>
<div class="category-list">
  <div class="col-md-4 reset-padding">
  <% @categories.each_with_index do |category, index| %>
    <%= link_to products_path(category: category.id), class: 'category-link' do %>
      <div class="category-item" style="background-image:url('<%= category.image_url %>'); background-size: cover;">
        <div class="category-info">
          <h2><%= category.title %></h2>
        </div>
      </div>
    <% end %>
    </div>
    <% if index == 0 || index == 1 %>
      <div class="col-md-8 reset-padding" >
    <% elsif index == 2 %>
      <div class="col-md-4 reset-padding">
    <% end %>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-md-3">
  <div class="product">
    <div class="product-image">
      <%= link_to (image_tag product.image_url(:small)), product if product.image? %>
      <div class="product-price">
        Price: <%= number_to_currency(product.price, precision: 2, separator: ',') %>
      </div>
    </div>
    <div class="product-title">
      <%= link_to product.title, product %>
    </div>
    <div class="product-action text-center">
      <%= button_to 'Buy', line_items_path(product_id: product), class: 'btn-buy' %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <%= render @products %>
</div>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<div>
  <%= image_tag @product.image_url(:big) %>
</div>
<div>
  <%= @product.description %>
</div>
<div>
  Price: <%= number_to_currency(@product.price, precision: 2, separator: ',') %>
</div>
<div>
  <%= link_to 'Купить', '#' %>
</div>